### PR TITLE
Include correct bookkeeper jars in pulsar-client jar

### PR DESCRIPTION
**Pull request by michaeljmarshall**
I encountered the following problem when using the pulsar client built from `2.8.0_ds`. It looks like we just need to include the right jars, so that they can be shaded.

I can also just push a commit to the branch, but I wanted the change reviewed before it gets merged.

```
   3144 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:150)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:115)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:73)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:411)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:66)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:319)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:374)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
	at org.apache.pulsar.common.allocator.PulsarByteBufAllocator.<clinit>(PulsarByteBufAllocator.java:58)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:92)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:74)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:153)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:134)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:65)
	at io.nosqlbench.driver.pulsar.PulsarActivity.initPulsarAdminAndClientObj(PulsarActivity.java:229)
	at io.nosqlbench.driver.pulsar.PulsarActivity.initActivity(PulsarActivity.java:118)
	at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.startActivity(ActivityExecutor.java:116)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:120)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:98)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:132)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:40)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:347)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:429)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:371)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:299)
	... 6 more
Caused by: java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:447)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:431)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/bookkeeper/common/allocator/LeakDetectionPolicy
	at org.apache.pulsar.common.allocator.PulsarByteBufAllocator.<clinit>(PulsarByteBufAllocator.java:58)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:92)
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:74)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:153)
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:134)
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:65)
	at io.nosqlbench.driver.pulsar.PulsarActivity.initPulsarAdminAndClientObj(PulsarActivity.java:229)
	at io.nosqlbench.driver.pulsar.PulsarActivity.initActivity(PulsarActivity.java:118)
	at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.startActivity(ActivityExecutor.java:116)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:120)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:98)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:132)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:40)
	at com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:292)
	at com.oracle.truffle.polyglot.HostToGuestCodeCache$1.executeImpl(HostToGuestCodeCache.java:86)
	at com.oracle.truffle.polyglot.GuestToHostRootNode.execute(GuestToHostRootNode.java:82)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:114)
	at com.oracle.truffle.polyglot.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:108)
	at com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:319)
	at com.oracle.truffle.polyglot.HostExecuteNode.doInvoke(HostExecuteNode.java:811)
	at com.oracle.truffle.polyglot.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:241)
	at com.oracle.truffle.polyglot.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:241)
	at com.oracle.truffle.polyglot.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:94)
	at com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:412)
	at com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:1390)
	at com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:1362)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:5989)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1481)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:292)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:238)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:721)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:154)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:80)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:302)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:124)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:214)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:99)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:941)
	at org.graalvm.polyglot.Context.eval(Context.java:347)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:429)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.bookkeeper.common.allocator.LeakDetectionPolicy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 56 more
```

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
Looks like this change is insufficient. I just got the following from the client:

```
java.lang.NoSuchMethodError: 'int com.scurrilous.circe.checksum.Crc32cIntChecksum.computeChecksum(org.apache.pulsar.shade.io.netty.buffer.ByteBuf)'
```

Testing out additional solutions.

**Review by eolivelli — COMMENTED** [review]
You are missing circe checksum library

**Review by nicoloboschi — APPROVED** [review]
LGTM, did you manage to get the client working ?

**Comment by michaeljmarshall** [comment]
> You are missing circe checksum library

@eolivelli - yes, I am. I wasn't sure if I needed to include any more jars, though. The current include statement in the `pom.xml` uses a wildcard. @nicoloboschi - does it make sense to use a wildcard here, or do we have to enumerate all dependencies from bookkeeper?

**Comment by michaeljmarshall** [comment]
@nicoloboschi - do you have a preference on whether or not to use the wildcard in the `includes` list?

**Comment by nicoloboschi** [comment]
unfortunately the groupId is the same as in Pulsar and BookKeeper for Datastax forks. so if you use wildcard you will end up including all the pulsar artifacts

**Review by nicoloboschi — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@nicoloboschi - thanks for merging. I believe that I did get the client to work based on this PR.

**Pull request merged**
