### PR TITLE
Fix subscription consumer count

### PR DESCRIPTION
**Pull request by cbornet**
Cherry-pick https://github.com/datastax/pulsar/commit/81927aa279ad2d9ac2bf732d7ea814411e8ebbff

### CODE REVIEW

**Comment by eolivelli** [comment]
@cbornet what's the status of this PR ?
should we merge it ? was it expected by some customer ?

**Comment by cbornet** [comment]
The cluster of the customer who had the issue was migrated to 2.10.
I think we don't have anymore 2.8.3 clusters.
So merging this will not do any harm but isn't strictly required.

**Comment by eolivelli** [comment]
closing 2.8.3 is mostly obsolete

**Comment by eolivelli** [comment]
thank you @cbornet for your clarification

**Pull request closed without merging**
