### PR TITLE
Pulsar shell: allow custom commands

### PR DESCRIPTION
**Pull request by eolivelli**
Without this change if you add custom commands you get a NPE.
Because setupCommands is running twice

### CODE REVIEW

**Comment by nicoloboschi** [comment]
@eolivelli could you add a stacktrace? 

setupCommands should be needed there to handle a couple of parameters that overrides the PulsarAdmin configuration

**Comment by eolivelli** [comment]
@nicoloboschi here you go
this is happening because we are calling `setupCommands` twice
```
java.lang.NullPointerException
	at org.apache.pulsar.admin.cli.PulsarAdminTool.addCommand(PulsarAdminTool.java:217)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.setupCommands(PulsarAdminTool.java:164)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:227)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:223)
	at org.apache.pulsar.shell.AdminShell.runCommand(AdminShell.java:72)
	at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:436)
	at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:220)
	at org.apache.pulsar.shell.PulsarShell.main(PulsarShell.java:209)
```

**Comment by eolivelli** [comment]
now setupCommands is called only here
https://github.com/datastax/pulsar/blob/d7f406ad4479909034648e43d10995129c8ae3e2/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java#L226

and additional root parameters are handled here
https://github.com/datastax/pulsar/blob/d7f406ad4479909034648e43d10995129c8ae3e2/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java#L243-L245

**Review by nicoloboschi — APPROVED** [review]

**Comment by nicoloboschi** [comment]
With this change the autocompletion for "admin" doesn't work anymore

**Pull request merged**
