### PR TITLE
Add debug for Proxy tests

### PR DESCRIPTION
**Pull request by eolivelli**
Add debug to understand the cause of this issue on CI

ava.lang.AssertionError: Connection should be failed due to hostnameVerification enabled
	at org.testng.Assert.fail(Assert.java:99)
	at org.apache.pulsar.proxy.server.ProxyWithAuthorizationTest.testTlsHostVerificationProxyToBroker(ProxyWithAuthorizationTest.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

### CODE REVIEW

**Comment by eolivelli** [comment]
@nicoloboschi @michaeljmarshall 
on CI the test fails because it is using "localhost" as broker dns name.
on my laptop the tests is using another IP address on my machine and not "localhost"

```
022-08-26T10:26:27,288+0000 INFO  [pulsar-client-io-317-1] o.a.p.c.i.ClientCnx@228 - [id: 0xb6a18f3e, L:/127.0.0.1:35018 - R:localhost/127.0.0.1:35319] localAddress /127.0.0.1:35018 remoteAddress localhost/127.0.0.1:35319 {}
2022-08-26T10:26:27,288+0000 INFO  [pulsar-client-io-317-1] o.a.p.c.i.ClientCnx@240 - [id: 0xb6a18f3e, L:/127.0.0.1:35018 - R:localhost/127.0.0.1:35319] Connected through proxy to target broker at localhost:38893 {}
2022-08-26T10:26:27,297+0000 INFO  [pulsar-proxy-io-312-6] o.a.p.p.s.ProxyConnection@164 - [/127.0.0.1:35018] New connection opened {}
2022-08-26T10:26:27,307+0000 INFO  [pulsar-proxy-io-312-6] o.a.p.p.s.ProxyConnection@550 - Created client conf tlsVer true serviceUrl pulsar+ssl://localhost:35319/ , tls true, dump ClientConfigurationData(serviceUrl=pulsar+ssl://localhost:35319/, serviceUrlProvider=null, authentication=org.apache.pulsar.client.impl.auth.AuthenticationTls@219f486c, authPluginClassName=null, authParams=null, authParamMap=null, operationTimeoutMs=30000, lookupTimeoutMs=30000, statsIntervalSeconds=60, numIoThreads=1, numListenerThreads=1, connectionsPerBroker=1, useTcpNoDelay=true, useTls=true, tlsTrustCertsFilePath=./src/test/resources/authentication/tls/ProxyWithAuthorizationTest/broker-cacert.pem, tlsAllowInsecureConnection=false, tlsHostnameVerificationEnable=true, concurrentLookupRequest=5000, maxLookupRequest=50000, maxLookupRedirects=20, maxNumberOfRejectedRequestPerConnection=50, keepAliveIntervalSeconds=30, connectionTimeoutMs=10000, requestTimeoutMs=60000, initialBackoffIntervalNanos=100000000, maxBackoffIntervalNanos=60000000000, enableBusyWait=false, listenerName=null, useKeyStoreTls=false, sslProvider=null, tlsTrustStoreType=JKS, tlsTrustStorePath=null, tlsTrustStorePassword=null, tlsCiphers=[], tlsProtocols=[], memoryLimitBytes=67108864, proxyServiceUrl=null, proxyProtocol=null, enableTransaction=false, clock=SystemClock[Etc/UTC], dnsLookupBindAddress=null, dnsLookupBindPort=0, socks5ProxyAddress=null, socks5ProxyUsername=null, socks5ProxyPassword=null) {}
2022-08-26T10:26:27,308+0000 INFO  [pulsar-proxy-io-312-6] o.a.p.p.s.ProxyConnection@286 - [/127.0.0.1:35018] complete connection, init proxy handler. authenticated with tls role Client, hasProxyToBrokerUrl: true {}
2022-08-26T10:26:27,343+0000 INFO  [pulsar-io-281-2] o.a.p.b.s.ServerCnx@289 - New connection from /127.0.0.1:50512 {}
```


this is the same log on my laptop
```
022-08-26T13:28:08,952+0200 INFO  [pulsar-client-io-93-1] o.a.p.c.i.ClientCnx@228 - [id: 0x165197aa, L:/192.168.1.111:54554 - R:/192.168.1.111:54548] localAddress /192.168.1.111:54554 remoteAddress /192.168.1.111:54548 {}
2022-08-26T13:28:08,952+0200 INFO  [pulsar-client-io-93-1] o.a.p.c.i.ClientCnx@240 - [id: 0x165197aa, L:/192.168.1.111:54554 - R:/192.168.1.111:54548] Connected through proxy to target broker at 192.168.1.111:54545 {}
2022-08-26T13:28:08,953+0200 INFO  [pulsar-proxy-io-88-6] o.a.p.p.s.ProxyConnection@164 - [/192.168.1.111:54554] New connection opened {}
2022-08-26T13:28:08,968+0200 INFO  [pulsar-proxy-io-88-6] o.a.p.p.s.ProxyConnection@550 - Created client conf tlsVer false serviceUrl pulsar+ssl://192.168.1.111:54548/ , tls true, dump ClientConfigurationData(serviceUrl=pulsar+ssl://192.168.1.111:54548/, serviceUrlProvider=null, authentication=org.apache.pulsar.client.impl.auth.AuthenticationTls@764f60d6, authPluginClassName=null, authParams=null, authParamMap=null, operationTimeoutMs=30000, lookupTimeoutMs=30000, statsIntervalSeconds=60, numIoThreads=1, numListenerThreads=1, connectionsPerBroker=1, useTcpNoDelay=true, useTls=true, tlsTrustCertsFilePath=./src/test/resources/authentication/tls/ProxyWithAuthorizationTest/broker-cacert.pem, tlsAllowInsecureConnection=false, tlsHostnameVerificationEnable=false, concurrentLookupRequest=5000, maxLookupRequest=50000, maxLookupRedirects=20, maxNumberOfRejectedRequestPerConnection=50, keepAliveIntervalSeconds=30, connectionTimeoutMs=10000, requestTimeoutMs=60000, initialBackoffIntervalNanos=100000000, maxBackoffIntervalNanos=60000000000, enableBusyWait=false, listenerName=null, useKeyStoreTls=false, sslProvider=null, tlsTrustStoreType=JKS, tlsTrustStorePath=null, tlsTrustStorePassword=null, tlsCiphers=[], tlsProtocols=[], memoryLimitBytes=67108864, proxyServiceUrl=null, proxyProtocol=null, enableTransaction=false, clock=SystemClock[Europe/Rome], dnsLookupBindAddress=null, dnsLookupBindPort=0, socks5ProxyAddress=null, socks5ProxyUsername=null, socks5ProxyPassword=null) {}
```

**Comment by eolivelli** [comment]
I tracked down the execution path and we are using this
https://github.com/datastax/pulsar/blob/a098cc1ab8a9bd3347280e7e5dcd4eb648d25572/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfigurationUtils.java#L46

**Comment by eolivelli** [comment]
maybe it is a matter of permissions on the machine ?
https://stackoverflow.com/questions/27200158/inetaddress-getlocalhost-gethostaddress-returning-unwanted-address-java

**Comment by nicoloboschi** [comment]
we moved CI to different machines and now it doesn't fail anymore, closing for now

**Pull request closed without merging**
